### ISSUE TITLE
Use of UUID in org file

### ISSUE THREAD

**Issue by borgauf** [fniessen/refcard-org-babel#5]
First, thanks for all your efforts to document and expand Emacs org-mode. This really helps me.

So I was looking at your refcard org babel, and I noticed your use of UUID. In [this](https://raw.githubusercontent.com/fniessen/refcard-org-babel/master/docs/header-args.org) file I see 

```
Header arguments can be set at different levels of a hierarchy:

1. [[id:7b0711cf-353b-4382-bc19-093e4e67ca92][*Default* header arguments]] shipped with Org mode
2. [[id:1cadb447-8403-400c-9117-13db017cc198][Default *languages-specific* header arguments]] shipped with Org mode
3. [[id:aebeec14-5693-4c38-8040-c91d28ade608][*Buffer* (or file) level header arguments]]
4. [[id:e7fda871-60ec-47d5-aee0-130c7d06fab2][*Subtree* header arguments]]
5. [[id:69939aec-bdee-449b-87fd-420daa53eaba][*Code block* header arguments]]
6. [[id:3fe40664-b445-4ae4-8248-8847576732fa][*Call line* header arguments]]
```

then I see 

```
** Default header arguments shipped with Org mode
   :PROPERTIES:
   :ID:       7b0711cf-353b-4382-bc19-093e4e67ca92
   :END:
- Variable ~org-babel-default-header-args~ for source blocks
```

Being a beginner, I don't really understand the "link"  `[[id:7b0711cf-353b-4382-bc19-093e4e67ca92][*Default* header arguments]] `or its use. And I am also curious about your use of UUID in your PROPERTIES drawer. There seems to be a connection between these two things, but I'm not getting it. Is this a bigblow thing, or a personal strategy of some sort? Sorry to ask this here, but your email address given in the raw org file doesn't work, i.e., fniessen@pirilampo.org

**Comment by fniessen** [comment]
Dear @borgauf, that's OK to ask this here. (And, indeed, I know since recently that my email address is not properly forwarded anymore -- need to fix it.)

For the id, it's quite simple:

- you have somewhere a target in the form: ID: xxx in the PROPERTIES drawer of "some section"; that's what you refer to.

- you may have, in different places, links to that section, by putting a link in the form of:
  [[id:xxx][some free text]] (where "some free text" may be "some section" or something else).

Is it more clear. Just experiment with an ECM (Minimal Complete Example) and you'll quickly understand this, if not yet clear.

Best regards.
